---
- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  delegate_to: localhost
  run_once: true
- name: Create group
  ansible.builtin.group:
    name: "{{ squid_group }}"
    state: present
    system: true
- name: Create user
  ansible.builtin.user:
    create_home: false
    group: "{{ squid_group }}"
    home: /var/spool/squid
    name: "{{ squid_user }}"
    shell: /sbin/nologin
    state: present
    system: true
- name: Install squid
  ansible.builtin.package:
    name: "{{ squid_packages }}"
    state: present
- name: Configure squid
  ansible.builtin.template:
    dest: "{{ squid_config_directory }}/{{ squid_config_file }}"
    mode: "0644"
    src: "{{ squid_config_file }}.j2"
    validate: squid -k parse -f %s
  notify:
    - Restart squid
- name: Create cache directory
  ansible.builtin.file:
    group: "{{ squid_group }}"
    mode: "0750"
    owner: "{{ squid_user }}"
    path: /var/spool/squid
    state: directory
- name: Flush_handlers
  ansible.builtin.meta: flush_handlers
- name: Start and enable squid
  ansible.builtin.service:
    enabled: true
    name: "{{ squid_service }}"
    state: started
  when:
    - not ansible_check_mode
